// <auto-generated />
namespace HMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Replaced_DoctorId_With_DoctorDepartmentId_In_Appointment_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Replaced_DoctorId_With_DoctorDepartmentId_In_Appointment_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121531094_Replaced_DoctorId_With_DoctorDepartmentId_In_Appointment_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
