// <auto-generated />
namespace HMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Appointment_Model_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appointment_Model_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201810091800042_Appointment_Model_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
