// <auto-generated />
namespace HMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserId_Added_To_EducationalQualification_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserId_Added_To_EducationalQualification_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201810080622450_UserId_Added_To_EducationalQualification_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
