// <auto-generated />
namespace HMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Altered_Blog_Model_Properties_To_Required_And_Added_Feature_Image_Property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altered_Blog_Model_Properties_To_Required_And_Added_Feature_Image_Property));
        
        string IMigrationMetadata.Id
        {
            get { return "201810181756449_Altered_Blog_Model_Properties_To_Required_And_Added_Feature_Image_Property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
